### ISSUE TITLE
Issue with figures that are connected to each other

### ISSUE THREAD

**Issue by chrise96** [tsaoyu/PyVisiLibity#1]
Also posted this issue on karlobermeyer's repo

The visibility polygon is improperly generated when sides of multiple figures are connected to each other (same coordinates).

I used the VisiLibity1 Python example to recreate this issue. See the image below. The blue line is the visibility polygon.

<img width="400" alt="Schermafbeelding 2020-04-01 om 16 42 10" src="https://user-images.githubusercontent.com/22835281/78255523-ad369100-74f7-11ea-8185-f13f4b6023fb.png">

**Comment by tsaoyu** [comment]
I don't think VisiLibity1 works well with polygons intersect. But I guess you can merge them into one to have a valid environment.
