### ISSUE TITLE
installtion of PyVisiLibity

### ISSUE THREAD

**Issue by dbeng965** [tsaoyu/PyVisiLibity#2]
Hello. 

I have been trying to install the PyVisiLibity in Python 3.7  (conda distribution), with:  
pip install visilibity 
But I got  this error:
![error](https://user-images.githubusercontent.com/64147694/79994504-fa31d580-84ad-11ea-8bbd-737e69269956.PNG)

Is the first time i see this error, and i don't konw how to fixe it, and  I don't even know what is the cause.
So I would appreciate if you could help me.

**Comment by tsaoyu** [comment]
On the Windows platform, you have to install the `swig` and Visual C++ 14.0. The former one can be installed in conda
```
conda install swig
```
and the later one can be download for free at https://visualstudio.microsoft.com/downloads/

**Comment by dbeng965** [comment]
Thanks for replying 

I do have swig but maybe the installation is cmpletely right. 
So I will try to fixe it... thanks a lot once again

**Comment by tsaoyu** [comment]
@dbeng965 Have this issue been resolved now? I am doing some tidy up on the inactive issues. Thanks

**Comment by tsaoyu** [comment]
Close due to inactive.
