### ISSUE TITLE
Hide the print functions

### ISSUE THREAD

**Issue by sheldonjinqi** [tsaoyu/PyVisiLibity#3]
Hi Yu Cao,

I was able to run the python binding following the instructions in ReadMe, but I am wondering if there is any way I can hide the print functions. For example the test code prints out the node being processed, the vertex index and cost to go, and it seems like all these are from the .cpp file not the visilibity_test.py. 

Thanks in advance for your help

**Comment by tsaoyu** [comment]
There is no easy way to do this as this code only wrap the original C++ code. If C++ code wants to print out a message, the python code will do so. An easier way in my mind is to (1) `>/dev/null` while you are running your Python code (2) disconnect underlying buffer from `std::cout` , e.g. from this [thread](https://stackoverflow.com/questions/30184998/how-to-disable-cout-output-in-the-runtime):

```c++
#include <iostream>

using namespace std;

int main(){

    // get underlying buffer
    streambuf* orig_buf = cout.rdbuf();

    // set null
    cout.rdbuf(NULL);

    cout << "this will not be displayed." << endl;

    // restore buffer
    cout.rdbuf(orig_buf);

    cout << "this will be dispalyed." << endl;

    return 0;
}
```

Rebuild the python extension and all print should go away.

**Comment by sheldonjinqi** [comment]
Thanks for your reply, I will give it a try. Since this is not really an issue, I am going to close it.
