### ISSUE TITLE
Error of VS in the installation 

### ISSUE THREAD

**Issue by lzr-thierry** [tsaoyu/PyVisiLibity#4]
I have installed Visual C++ 14.0 and swig. But when I tried "pip install visilibity" on my computer, there were some errors in VS.
![屏幕截图 2022-02-13 194904](https://user-images.githubusercontent.com/73570458/153751751-05f7726c-085a-4d8b-91ac-6db7f807a357.png)

**Comment by tsaoyu** [comment]
This seems the behaviour of original C++ Visilibity, you can try uncomment the following lines if you're compling with MSVC.
https://github.com/tsaoyu/PyVisiLibity/blob/master/visilibity.hpp#L48

**Comment by lzr-thierry** [comment]
> This seems the behaviour of original C++ Visilibity, you can try uncomment the following lines if you're compling with MSVC. https://github.com/tsaoyu/PyVisiLibity/blob/master/visilibity.hpp#L48

The installation is successful ! Thank you very much !
